### ISSUE TITLE
Research before project start

### ISSUE THREAD

**Issue by oKiselov** [AprioritWebCalendar/AprioritWebCalendar#1]
It is necessary to do research about existing web calendars, their features, architectures, rules etc.

**Comment by oKiselov** [comment]
Info: 
- http://www.ietf.org/rfc/rfc2445.txt - international specification; 
- https://www.npmjs.com/package/ng-fullcalendar - package fullcalendar module for Angular 2, 4, 5; 
- https://fullcalendar.io/ - A JavaScript event calendar.

**Comment by AprioritWebCalendar** [comment]
https://github.com/rianjs/ical.net - iCal.NET is an iCalendar (RFC 5545) class library for .NET aimed at providing RFC 5545 compliance, while providing full compatibility with popular calendaring applications and libraries.

**Comment by oKiselov** [comment]
https://github.com/rianjs/ical.net - iCal.NET is an iCalendar (RFC 5545) class library for .NET aimed at providing RFC 5545 compliance, while providing full compatibility with popular calendaring applications and libraries.

**Comment by YurkoUA** [comment]
Calendar: https://angular-material-calendar.bradb.net - it's also good calendar, supports full-screen mode, looks like Google Calendar

Datepicker: https://material.angularjs.org/latest/demo/datepicker

HangFire - library that runs tasks by schedule. It'll help us to send notifications about events.
https://www.hangfire.io/

Googe Calendar API:
https://www.nuget.org/packages/Google.Apis.Calendar.v3/ - nuget package, works with api. We may use it to synchronize events with Google.

EvoPDF - a library that creates PDF files from HTML page. We may use it to print timetable by day/week/...
The free version of library inserts a big title on the page. But it's ok as for our trainee-project.
https://www.nuget.org/packages/EvoPDF/

**Comment by YurkoUA** [comment]
About front-end:

- Integrating Google Maps in Angular 5: https://blog.cloudboost.io/integrating-google-maps-in-angular-5-ca5f68009f29
- Recaptcha component for Angular 5: https://www.npmjs.com/package/angular5-recaptcha
- Nice Bootstrap snippets: https://bootsnipp.com/

**Comment by YurkoUA** [comment]
t

**Comment by YurkoUA** [comment]
Scripts that create "system" Identity tables:

https://www.dropbox.com/sh/4jvl2g69p4ijr7k/AACxOqmjYsWZgbXDAUkMLsa1a?dl=0

**Comment by YurkoUA** [comment]
A good example of Angular 2+ application:

https://github.com/Igorgolyak5/angular2-spring
