### ISSUE TITLE
Features of the application

### ISSUE THREAD

**Issue by yuriimustafin** [AprioritWebCalendar/AprioritWebCalendar#4]
# Features of minimum viable product:
## Operations with events:
- Create (quick submit or creating with a declaration of all public properties)
- Change (drag'n'drop time changing, changing of all properties in edit mode)
- Delete an item

## Properties of events:
- Name
- Category
- Calendars
- Members (required and optional)
- Description
- Date and time (start and end)
- Access parameters (private/public)
- Status (busy, available, etc)
- Notification mode (SMS, TG, e-mail, etc)
- Place
- Priority

## Types of events:
- `Event` - has a start and an end time, can be recurring 
- `To-do item` - is an event that has not time data, only a day (all-day event)
- `Task` - is a to-do item or an event that has progress status (done, started, not begun)

## Security and authorization
Calendars can be public and private. Anyone can read a public calendar. A private calendar can be shared with other users. 
An event can be shared with other users (they can be invited as a member). Even private calendars can have shared events (without sharing full calendar)
Some calendars can be grouped into organization structures with declared roles with specified read-write access. 

## Synchronization 
Supporting of ICAL and/or CalDav protocols for synchronization and importing data.

# Extended functionality
- Voice input
  - Using Web Speech API for adding or changing events
- Telegram bot
  - Using a bot for notification users about upcoming events
  - Using a bot for creating and editing events
- Multiple time zones view
- Signing up via social
- Search
- Hotkeys
- Synchronization with FB events via their API
- Providing some features as a premium account (with supporting payments and appropriate access rights)
- Managing  projects:
  - Creating tasks with progress status 
  - Tasks can depend on each other
  - Assign tasks to users
  - Check project status

**Comment by AprioritWebCalendar** [comment]
<h3>Functionality of minimum viable product in advance (deadline - 01.04.2018)</h3>

| **Data Access Layer** | **Business Layer** | **Presentation Layer** |
|---------------------|-----------------|----------------------|
| Identity schema. Roles: SuperUserApp, OrganizationUser, SimpleUser | **UserRegistrationService** and **UserAuthenticationService** (tokens, validation etc) | Registration / Login View 
| DB schema **according to iCal** standard with CRUD operations for **calendars, events, todo, tasks entities**. | **CommonCalendarService** - operations with CRUD functionality of calendars, share calendars, groups of calendars: private, public, group private. | MainCalendarView - small calendar, event division module, ToDos module, inbox for messages and notifications
| Mapping of entities in Fluent API style | **EventCalendarService** - operations with CRUD functionality of events, share events, invitations to events, groups of events: private, public, group private | Settings View - colors, datetime zones, management for own calendars, export and import of *.ics files with calendars according to iCal
| Relations in advance : User - Calendar = M-to-M; Event - Calendar = M-to-M; User - Event = M-to-M (the same with ToDo and Tasks) | **ToDoCalendarService** - operations with CRUD functionality of ToDo, share ToDos. | 
| | **TaskCalendarService** - should realize points of iCal standard in case of free / busy activities of User |  
| | **NotificationService** - reactive architecture principles, notifications, alerts and signals about events, reminders, pool of tasks and jobs which will work as a daemon application **(the need for details)**

**Comment by oKiselov** [comment]
<h3>Functionality of minimum viable product in advance (deadline - 01.04.2018)</h3>

| **Data Access Layer** | **Business Layer** | **Presentation Layer** |
|---------------------|-----------------|----------------------|
| Identity schema. Roles: SuperUserApp, OrganizationUser, SimpleUser | **UserRegistrationService** and **UserAuthenticationService** (tokens, validation etc) | Registration / Login View 
| DB schema **according to iCal** standard with CRUD operations for **calendars, events, todo, tasks entities**. | **CommonCalendarService** - operations with CRUD functionality of calendars, share calendars, groups of calendars: private, public, group private. | MainCalendarView - small calendar, event division module, ToDos module, inbox for messages and notifications
| Mapping of entities in Fluent API style | **EventCalendarService** - operations with CRUD functionality of events, share events, invitations to events, groups of events: private, public, group private | Settings View - colors, datetime zones, management for own calendars, export and import of *.ics files with calendars according to iCal
| Relations in advance : User - Calendar = M-to-M; Event - Calendar = M-to-M; User - Event = M-to-M (the same with ToDo and Tasks) | **ToDoCalendarService** - operations with CRUD functionality of ToDo, share ToDos. | 
| | **TaskCalendarService** - should realize points of iCal standard in case of free / busy activities of User |  
| | **NotificationService** - reactive architecture principles, notifications, alerts and signals about events, reminders, pool of tasks and jobs which will work as a daemon application **(the need for details)**

**Comment by YurkoUA** [comment]
Are `To-do item` and `Task` related with a calendar or jusr with a user?

**Comment by YurkoUA** [comment]
A scheme of the Database.
Write your email and I'll share the scheme with you and you'll be able to edit it.

![screenshot_1](https://user-images.githubusercontent.com/12056226/37795058-03585a0c-2e1c-11e8-8a2a-08a719aa5c5b.png)

**Comment by YurkoUA** [comment]
I suggest this template for front-end. The left panel we might use for check boxes with calendars that user wants to show.

https://getbootstrap.com/docs/3.3/examples/dashboard/
